

import { Camp, Review } from './types';

const sampleReviews: { [key: number]: Review[] } = {
    1: [
        { authorName: 'Familia García', authorAvatar: 'https://i.pravatar.cc/150?u=garcia', rating: 5, text: '¡Nuestros hijos volvieron encantados! Las actividades en la naturaleza son fantásticas y los monitores muy atentos.' },
        { authorName: 'Elena Rodríguez', authorAvatar: 'https://i.pravatar.cc/150?u=elena', rating: 4, text: 'Muy buena organización. Mi hija aprendió mucho sobre el medio ambiente y se divirtió a lo grande.' }
    ],
    2: [
        { authorName: 'Marcos Soler', authorAvatar: 'https://i.pravatar.cc/150?u=marcos', rating: 5, text: 'Si a tu hijo/a le gustan los deportes de agua, este es su campamento. El entorno del embalse es espectacular.' },
        { authorName: 'Lucía Jiménez', authorAvatar: 'https://i.pravatar.cc/150?u=lucia', rating: 5, text: 'Una experiencia inolvidable. El equipo de monitores es profesional y muy cercano. ¡Repetiremos seguro!' }
    ],
    3: [
        { authorName: 'Pedro Navarro', authorAvatar: 'https://i.pravatar.cc/150?u=pedro', rating: 4, text: 'La granja escuela es una maravilla. Los niños aprenden de verdad a cuidar de los animales. Muy recomendable.' }
    ],
    // ... add more sample reviews for other camps if needed
};


export const CAMPS_DATA: Camp[] = [
  {
    id: 1,
    name: 'Albergue Actio',
    location: 'Alborache, Valencia',
    description: 'Actividades en la naturaleza y talleres medioambientales.',
    longDescription: 'En el Albergue Actio ofrecemos una amplia variedad de actividades pensadas para disfrutar de la naturaleza, aprender y convivir en grupo. Entre ellas se incluyen rutas de senderismo, talleres medioambientales, actividades de aventura como tirolina o escalada, y juegos cooperativos que fomentan el trabajo en equipo. También organizamos gymkanas, veladas nocturnas y dinámicas educativas, adaptadas a todas las edades. Nuestro objetivo es combinar diversión, aprendizaje y respeto por el entorno natural.',
    mainImage: 'https://picsum.photos/seed/actio/800/250',
    images: [
      'https://picsum.photos/seed/actio1/600/400',
      'https://picsum.photos/seed/actio2/600/400',
      'https://picsum.photos/seed/actio3/600/400',
      'https://picsum.photos/seed/actio4/600/400',
      'https://picsum.photos/seed/actio5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+Albergue+Actio',
    contactPhone: '+34 961 234 567',
    contactEmail: 'info@actio.es',
    highlights: ['Nature', 'Adventure', 'Arts'],
    price: 250,
    reviews: sampleReviews[1],
  },
  {
    id: 2,
    name: 'Benagéber',
    location: 'Benagéber, Valencia',
    description: 'Aventura y deportes acuáticos en el embalse.',
    longDescription: 'El campamento de Benagéber es ideal para los amantes de los deportes acuáticos. Ubicado a orillas del embalse, ofrece actividades como piragüismo, paddle surf y vela. Además, complementamos la experiencia con rutas de senderismo por la serranía, juegos de orientación y talleres de supervivencia. Las noches se llenan de magia con nuestras veladas de astronomía y juegos nocturnos.',
    mainImage: 'https://picsum.photos/seed/benageber/800/250',
    images: [
      'https://picsum.photos/seed/benageber1/600/400',
      'https://picsum.photos/seed/benageber2/600/400',
      'https://picsum.photos/seed/benageber3/600/400',
      'https://picsum.photos/seed/benageber4/600/400',
      'https://picsum.photos/seed/benageber5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+Benagéber',
    contactPhone: '+34 962 123 456',
    contactEmail: 'reservas@benageber.com',
    highlights: ['Adventure', 'Water', 'Sports'],
    price: 320,
    reviews: sampleReviews[2],
  },
  {
    id: 3,
    name: 'Campamento la Serrana',
    location: 'Buñol, Valencia',
    description: 'Inmersión en la vida rural y actividades de granja escuela.',
    longDescription: 'La Serrana ofrece una experiencia única de inmersión en la vida rural. Los participantes aprenderán a cuidar de los animales de la granja, cultivar en el huerto ecológico y elaborar productos artesanales como pan y queso. Combinamos estas tareas con juegos tradicionales, talleres de manualidades con materiales reciclados y excursiones para conocer la flora y fauna local.',
    mainImage: 'https://picsum.photos/seed/serrana/800/250',
    images: [
      'https://picsum.photos/seed/serrana1/600/400',
      'https://picsum.photos/seed/serrana2/600/400',
      'https://picsum.photos/seed/serrana3/600/400',
      'https://picsum.photos/seed/serrana4/600/400',
      'https://picsum.photos/seed/serrana5/600/400',
    ],
     officialSite: 'https://www.google.com/search?q=Campamento+La+Serrana+Buñol',
     contactPhone: '+34 963 345 678',
     contactEmail: 'contacto@laserrana.org',
     highlights: ['Nature', 'Arts'],
     price: 280,
     reviews: sampleReviews[3],
  },
  {
    id: 4,
    name: 'Campus Moragete',
    location: 'Requena, Valencia',
    description: 'Enfoque en el desarrollo de habilidades y trabajo en equipo.',
    longDescription: 'Moragete está diseñado para potenciar el crecimiento personal y el trabajo en equipo. A través de dinámicas de grupo, retos de ingenio y actividades deportivas, los campistas desarrollarán habilidades de liderazgo, comunicación y resolución de problemas. El programa también incluye talleres creativos, veladas temáticas y mucho espacio para la diversión y la amistad.',
    mainImage: 'https://picsum.photos/seed/moragete/800/250',
    images: [
      'https://picsum.photos/seed/moragete1/600/400',
      'https://picsum.photos/seed/moragete2/600/400',
      'https://picsum.photos/seed/moragete3/600/400',
      'https://picsum.photos/seed/moragete4/600/400',
      'https://picsum.photos/seed/moragete5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+Campus+Moragete',
    contactPhone: '+34 964 456 789',
    contactEmail: 'campus@moragete.net',
    highlights: ['Sports', 'Adventure'],
    price: 300,
  },
  {
    id: 5,
    name: 'Cumbres Alegres',
    location: 'Cofrentes, Valencia',
    description: 'Exploración de la montaña y actividades de aventura.',
    longDescription: 'Para los más aventureros, Cumbres Alegres es el destino perfecto. El programa incluye escalada en rocódromo, rappel, tiro con arco y rutas de BTT por parajes espectaculares. Los campistas aprenderán técnicas de orientación y supervivencia, y disfrutarán de la naturaleza en su estado más puro, siempre bajo la supervisión de monitores especializados.',
    mainImage: 'https://picsum.photos/seed/cumbres/800/250',
    images: [
      'https://picsum.photos/seed/cumbres1/600/400',
      'https://picsum.photos/seed/cumbres2/600/400',
      'https://picsum.photos/seed/cumbres3/600/400',
      'https://picsum.photos/seed/cumbres4/600/400',
      'https://picsum.photos/seed/cumbres5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+Cumbres+Alegres+Cofrentes',
    contactPhone: '+34 965 567 890',
    contactEmail: 'aventura@cumbresalegres.es',
    highlights: ['Adventure', 'Nature', 'Sports'],
    price: 350,
  },
  {
    id: 6,
    name: 'Denia Water Sports Camp',
    location: 'Denia, Alicante',
    description: 'Campamento de verano centrado en deportes acuáticos y playa.',
    longDescription: 'Disfruta del Mediterráneo en nuestro campamento en Denia. La semana está repleta de actividades como vela, windsurf, snorkel y kayak. Además de los deportes acuáticos, organizamos juegos en la playa, talleres sobre el ecosistema marino y excursiones en barco. Una combinación perfecta de deporte, aprendizaje y diversión bajo el sol.',
    mainImage: 'https://picsum.photos/seed/denia/800/250',
    images: [
      'https://picsum.photos/seed/denia1/600/400',
      'https://picsum.photos/seed/denia2/600/400',
      'https://picsum.photos/seed/denia3/600/400',
      'https://picsum.photos/seed/denia4/600/400',
      'https://picsum.photos/seed/denia5/600/400',
    ],
     officialSite: 'https://www.google.com/search?q=Campamento+deportes+acuáticos+Denia',
     contactPhone: '+34 966 678 901',
     contactEmail: 'info@deniawatersports.com',
     highlights: ['Water', 'Sports'],
     price: 400,
  },
  {
    id: 7,
    name: 'Taume l',
    location: 'Serra, Valencia',
    description: 'Aventura y naturaleza en el corazón de la Sierra Calderona.',
    longDescription: 'Taume l se encuentra en un entorno privilegiado, el Parque Natural de la Sierra Calderona. Es el lugar ideal para los amantes del senderismo y la naturaleza. Organizamos rutas interpretativas, talleres de rastreo de fauna, juegos de pistas y vivacs para dormir bajo las estrellas. Todo ello fomentando el compañerismo y el respeto por el medio ambiente.',
    mainImage: 'https://picsum.photos/seed/taume/800/250',
    images: [
      'https://picsum.photos/seed/taume1/600/400',
      'https://picsum.photos/seed/taume2/600/400',
      'https://picsum.photos/seed/taume3/600/400',
      'https://picsum.photos/seed/taume4/600/400',
      'https://picsum.photos/seed/taume5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+Taume+l+Serra',
    contactPhone: '+34 967 789 012',
    contactEmail: 'hola@taumel.es',
    highlights: ['Nature', 'Adventure'],
    price: 290,
  },
   {
    id: 8,
    name: 'San Juan Bosco',
    location: 'Godelleta, Valencia',
    description: 'Campamento con piscina y gran variedad de deportes.',
    longDescription: 'En San Juan Bosco la diversión está garantizada. Contamos con unas magníficas instalaciones que incluyen piscina, pistas polideportivas y amplias zonas verdes. El programa combina actividades acuáticas, torneos deportivos (fútbol, baloncesto, voleibol) y grandes juegos grupales, sin olvidar los talleres creativos y las veladas nocturnas que hacen de cada día una experiencia inolvidable.',
    mainImage: 'https://picsum.photos/seed/bosco/800/250',
    images: [
      'https://picsum.photos/seed/bosco1/600/400',
      'https://picsum.photos/seed/bosco2/600/400',
      'https://picsum.photos/seed/bosco3/600/400',
      'https://picsum.photos/seed/bosco4/600/400',
      'https://picsum.photos/seed/bosco5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+San+Juan+Bosco+Godelleta',
    contactPhone: '+34 968 890 123',
    contactEmail: 'sanjuanbosco@camp.com',
    highlights: ['Sports', 'Water'],
    price: 275,
  },
   {
    id: 9,
    name: 'Olocau',
    location: 'Olocau, Valencia',
    description: 'Historia y naturaleza a los pies de la Sierra Calderona.',
    longDescription: 'El campamento de Olocau ofrece una mezcla fascinante de historia y naturaleza. Organizamos excursiones al Castillo del Real y al poblado íbero del Puntal dels Llops para que los campistas descubran el rico patrimonio de la zona. Estas actividades culturales se combinan con juegos en la naturaleza, talleres de arqueología, rutas de senderismo y refrescantes baños en la piscina.',
    mainImage: 'https://picsum.photos/seed/olocau/800/250',
    images: [
      'https://picsum.photos/seed/olocau1/600/400',
      'https://picsum.photos/seed/olocau2/600/400',
      'https://picsum.photos/seed/olocau3/600/400',
      'https://picsum.photos/seed/olocau4/600/400',
      'https://picsum.photos/seed/olocau5/600/400',
    ],
    officialSite: 'https://www.google.com/search?q=Campamento+Olocau',
    contactPhone: '+34 969 901 234',
    contactEmail: 'info@olocauaventura.es',
    highlights: ['Nature', 'Adventure', 'Arts'],
    price: 310,
  },
];