-- MySQL Script generated by MySQL Workbench
-- Thu Mar 27 10:31:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema campamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campamento` DEFAULT CHARACTER SET utf8 ;
USE `campamento` ;

-- -----------------------------------------------------
-- Table `campamento`.`CAMPAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`CAMPAMENTO` (
  `codigo` INT NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`FAMILIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`FAMILIA` (
  `dni_fam` CHAR(9) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(30) NULL,
  PRIMARY KEY (`dni_fam`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`MONITOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`MONITOR` (
  `dni_monitor` CHAR(9) NOT NULL,
  `codigo_campa` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`dni_monitor`),
  INDEX `fk_MONITOR_CAMPAMENTO_idx` (`codigo_campa` ASC),
  CONSTRAINT `fk_MONITOR_CAMPAMENTO`
    FOREIGN KEY (`codigo_campa`)
    REFERENCES `campamento`.`CAMPAMENTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`GRUPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`GRUPO` (
  `codigo_grupo` INT NOT NULL,
  `dni_monitor` CHAR(9) NOT NULL,
  `id` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo_grupo`),
  INDEX `fk_GRUPO_MONITOR_idx` (`dni_monitor` ASC),
  CONSTRAINT `fk_GRUPO_MONITOR`
    FOREIGN KEY (`dni_monitor`)
    REFERENCES `campamento`.`MONITOR` (`dni_monitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`NIÑOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`NIÑOS` (
  `dni_niño` CHAR(9) NOT NULL,
  `dni_fam` CHAR(9) NOT NULL,
  `codigo_grupo` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `edad` INT NOT NULL,
  `otros` VARCHAR(50) NULL,
  PRIMARY KEY (`dni_niño`),
  INDEX `fk_NIÑOS_FAMILIA_idx` (`dni_fam` ASC),
  INDEX `fk_NIÑOS_GRUPO_idx` (`codigo_grupo` ASC),
  CONSTRAINT `fk_NIÑOS_FAMILIA`
    FOREIGN KEY (`dni_fam`)
    REFERENCES `campamento`.`FAMILIA` (`dni_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NIÑOS_GRUPO`
    FOREIGN KEY (`codigo_grupo`)
    REFERENCES `campamento`.`GRUPO` (`codigo_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`ACUDEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`ACUDEN` (
  `codigo_campa` INT NOT NULL,
  `dni_niño` CHAR(9) NOT NULL,
  PRIMARY KEY (`codigo_campa`, `dni_niño`),
  INDEX `fk_ACUDEN_NIÑOS_idx` (`dni_niño` ASC),
  CONSTRAINT `fk_ACUDEN_CAMPAMENTO`
    FOREIGN KEY (`codigo_campa`)
    REFERENCES `campamento`.`CAMPAMENTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACUDEN_NIÑOS`
    FOREIGN KEY (`dni_niño`)
    REFERENCES `campamento`.`NIÑOS` (`dni_niño`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`PAGO` (
  `codigo_campa` INT NOT NULL,
  `dni_fam` CHAR(9) NOT NULL,
  `cuenta_bancaria` VARCHAR(19) NOT NULL,
  `fecha_caducidad` DATE NOT NULL,
  `cvc` CHAR(3) NOT NULL,
  PRIMARY KEY (`codigo_campa`, `dni_fam`),
  INDEX `fk_PAGO_FAMILIA_idx` (`dni_fam` ASC),
  CONSTRAINT `fk_PAGO_CAMPAMENTO`
    FOREIGN KEY (`codigo_campa`)
    REFERENCES `campamento`.`CAMPAMENTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGO_FAMILIA`
    FOREIGN KEY (`dni_fam`)
    REFERENCES `campamento`.`FAMILIA` (`dni_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`ACTIVIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`ACTIVIDADES` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `campamento`.`REALIZAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campamento`.`REALIZAN` (
  `codigo_grupo` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`codigo_grupo`, `id`),
  INDEX `fk_REALIZAN_ACTIVIDADES_idx` (`id` ASC),
  CONSTRAINT `fk_REALIZAN_GRUPO`
    FOREIGN KEY (`codigo_grupo`)
    REFERENCES `campamento`.`GRUPO` (`codigo_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REALIZAN_ACTIVIDADES`
    FOREIGN KEY (`id`)
    REFERENCES `campamento`.`ACTIVIDADES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

